manipulator:
  kinematics_solver: motoman_sia20d_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.01
  kinematics_solver_attempts: 10
manipulator_asus:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.01
  kinematics_solver_attempts: 10
manipulator_tcp:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.01
  kinematics_solver_attempts: 10
